version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: znotes-postgres
    environment:
      POSTGRES_USER: znotes
      POSTGRES_PASSWORD: znotes123
      POSTGRES_DB: znotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - znotes-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: znotes-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - znotes-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: znotes-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://znotes:znotes123@postgres:5432/znotes?schema=public"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: "development"
      PORT: "3000"
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - znotes-network
    command: npm run start:dev

volumes:
  postgres_data:
  redis_data:

networks:
  znotes-network:
    driver: bridge