version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: noteflow-postgres-dev
    environment:
      POSTGRES_USER: znotes
      POSTGRES_PASSWORD: znotes123
      POSTGRES_DB: znotes
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - noteflow-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U znotes"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Redis Cache for Development
  redis:
    image: redis:7-alpine
    container_name: noteflow-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - noteflow-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  noteflow-dev-network:
    driver: bridge